### ISSUE TITLE
Remote harvesters not shown in full node

### ISSUE THREAD

**Issue by smilstea** [foxypool/chives-blockchain#21]
I have several remote harvesters for chia and chives. With the recent gui changes in chia and chives, in chia under plots I see each remote harvester and plot count and on the farm tab the total size of all harvesters, with chives I only see the local harvester in the plots tab and my total on the farm tab is just of the local harvester.
However, in the foxypool monitoring webpage it shows my entire farm (on my farm tab 89tb and around 550tb on the website), as well in my plots passed filter i see entries for the size of my remote harvesters so i know i am farming all 550tb. Before the latest chives release I used to see my entire farm size in the farm tab on my full node but the ability to see remote harvesters didn't exist yet.

**Comment by felixbrucker** [comment]
There are several reasons why this might be, including:
- incompatible harvester versions
- chives plain having a bug somewhere

Either way this is not an issue with the og patches done here, you will probably want to check out the official chives repo or their discord for that

**Comment by smilstea** [comment]
Thank you for your response.
I was on 1.2.11 og 1.1.0 on my remote harvesters. After upgrading to 1.3.1
og 1.1.1 it works properly.

**Comment by felixbrucker** [comment]
Great 👍
